server:
   port: 2001
   servlet:
      context-path: /notification-service

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs
  api-docs:
    path: /v3/api-docs